package com.example.wildlauncher;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

import java.sql.*;
import java.sql.DriverManager;

public class Database {
    /*public Connection establishConnection() throws SQLException {
        Connection connection = null;
        try {
            connection = DriverManager.getConnection("jdbc:derby:applicationDB;create=true");
            connection.setAutoCommit(false);
            System.out.println("Connection to Database was successfull!");
        } catch (SQLException e) {
            e.printStackTrace();
            throw e;
        }
        return connection;
    }*/

    public static void createActivityTable() throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:derby:applicationDB;create=true");

        String CREATE_TABLE_SQL_INSTRUCTIONS = "CREATE TABLE APPLICATIONS (" +
                "ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY, " +
                "NAME VARCHAR(255), " +
                "PATH VARCHAR(255), " +
                "SCRIPTPATH VARCHAR(255), " +
                "PRIMARY KEY (ID))";
        try (Statement instructions = connection.createStatement()) {
            instructions.executeUpdate(CREATE_TABLE_SQL_INSTRUCTIONS);
            System.out.println("Table created");
        } catch (SQLException e) {
            if (e.getSQLState().equals("X0Y32")) {
                System.out.println("The Table 'APPLICATIONS' already exists.");

            } else {
                e.printStackTrace();
            }
        }

    }

    public static void addApplicationToTable(String name, String path, String scriptPath) throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:derby:applicationDB;create=true");

        String ADD_TO_TABLE_SQL_INSTRUCTIONS = "INSERT INTO APPLICATIONS (NAME, PATH, SCRIPTPATH) VALUES (?, ?, ?)";

        try (PreparedStatement addToTableSQLInstructions = connection.prepareStatement(ADD_TO_TABLE_SQL_INSTRUCTIONS)) {
            addToTableSQLInstructions.setString(1, name);
            addToTableSQLInstructions.setString(2, path);
            addToTableSQLInstructions.setString(3, scriptPath);
            addToTableSQLInstructions.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void editApplicationInTable(int id, String name, String path, String scriptPath) throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:derby:applicationDB;create=true");

        String EDIT_IN_TABLE_SQL_INSTRUCTIONS = "UPDATE APPLICATIONS SET NAME = (?), PATH = (?), SCRIPTPATH = (?) " +
                "WHERE (ID) = (?)";

        try (PreparedStatement editInTableSQLInstructions = connection.prepareStatement(EDIT_IN_TABLE_SQL_INSTRUCTIONS)) {
            editInTableSQLInstructions.setString(1, name);
            editInTableSQLInstructions.setString(2, path);
            editInTableSQLInstructions.setString(3, scriptPath);
            editInTableSQLInstructions.setInt(4, id);
            editInTableSQLInstructions.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static ObservableList<Application> getApplicationsFromTable() throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:derby:applicationDB;create=true");

        ObservableList<Application> applications = FXCollections.observableArrayList();
        String SELECT_FROM_TABLE_INSTRUCTIONS = "SELECT * FROM APPLICATIONS";
        try (PreparedStatement query = connection.prepareStatement(SELECT_FROM_TABLE_INSTRUCTIONS);
            ResultSet result = query.executeQuery()) {
            while (result.next()) {
                Application application = new Application(
                        result.getInt("ID"),
                        result.getString("NAME"),
                        result.getString("PATH"),
                        result.getString("SCRIPTPATH")
                );
                applications.add(application);
            }
        }
        return applications;
    }

    public static void deleteApplication(int id) throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:derby:applicationDB;create=true");

        String DELETE_FROM_TABLE_SQL_INSTRUCTIONS = "DELETE FROM APPLICATIONS WHERE ID = (?)";

        try (PreparedStatement deleteFromTableSQLInstructions = connection.prepareStatement(DELETE_FROM_TABLE_SQL_INSTRUCTIONS)) {
            deleteFromTableSQLInstructions.setInt(1, id);
            deleteFromTableSQLInstructions.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


}
